//%attributes = {"invisible":true}
/*

prepare synthetic queries generated by LLM for next data mining
updates: TrainingSearchx2,TrainingPassage

run once for each new model

*/

var $client : cs:C1710.AIKit.OpenAI
$client:=cs:C1710.AIKit.OpenAI.new({baseURL: "http://127.0.0.1:"+String:C10(Storage:C1525.port.embeddings)+"/v1"})

var $model : Text
$model:="bge-m3-r2"
var $params : cs:C1710.AIKit.OpenAIEmbeddingsParameters
$params:=cs:C1710.AIKit.OpenAIEmbeddingsParameters.new()

var $search : cs:C1710.TrainingSearchEntity
For each ($search; ds:C1482.TrainingSearch.all())
	var $batch : Object
	$batch:=$client.embeddings.create($search.text; $model; $params)
	If ($batch.success)
		$search.embeddings:=$batch.embedding.embedding
		$search.meta.model:=$model
		var $passage : cs:C1710.TrainingPassageEntity
		$passage:=$search.passage
		$batch:=$client.embeddings.create($passage.text; $model; $params)
		If ($batch.success)
			$passage.embeddings:=$batch.embedding.embedding
			$passage.save()
			$search.similarity:=$search.embeddings.cosineSimilarity($passage.embeddings)
			$search.save()
		End if 
	End if 
End for each 