//%attributes = {"invisible":true}
/*

prepare synthetic queries generated by LLM for next data mining
updates: TrainingSearchx2,TrainingPassage

run once for each new model

embeddings:    vectors from base model
newEmbeddings: vectors from current model
drift:         cosine similarity shift

for training, we mine passages where

- positive is true
- newSimilarity is high 
- (base) similarity is moderate

*/

var $client : cs:C1710.AIKit.OpenAI
$client:=cs:C1710.AIKit.OpenAI.new({baseURL: "http://127.0.0.1:"+String:C10(Storage:C1525.port.embeddings)+"/v1"})

var $model : Text
$model:="bge-m3-r2"
var $params : cs:C1710.AIKit.OpenAIEmbeddingsParameters
$params:=cs:C1710.AIKit.OpenAIEmbeddingsParameters.new()

var $search : cs:C1710.TrainingSearchEntity

$all:=ds:C1482.TrainingSearch.all()
//ds.TrainingSearch.query("meta.newModel != :1"; $model)
For each ($search; $all)
	var $batch : Object
	$batch:=$client.embeddings.create($search.text; $model; $params)
	If ($batch.success)
		$search.newEmbeddings:=$batch.embedding.embedding
		$search.meta.newModel:=$model
		var $passage : cs:C1710.TrainingPassageEntity
		$passage:=$search.passage
		$batch:=$client.embeddings.create($passage.text; $model; $params)
		If ($batch.success)
			$passage.newEmbeddings:=$batch.embedding.embedding
			$passage.meta.newModel:=$model
			$passage.save()
			$search.newSimilarity:=$search.newEmbeddings.cosineSimilarity($passage.newEmbeddings)
			$search.drift:=$search.newSimilarity-$search.similarity  //direction matters
			$search.save()
		End if 
	End if 
End for each 